### PR TITLE
WIP: make `--list` conistant with running WRT `-e`

### LINKED ISSUE #217: -e *adds* to host test list when using --list, but *overrides* mbed host tests when actually running
Repro steps:

Use mbed test with -e to add a folder for custom host tests, and run all unit tests.  Any mbed unit test needing any of the "out of the box" host tests ( those that live in tools/host_tests ) will fail, saying it can't find tests like "RTCTest"

Although invoking mbedhtrun --list -e custom/host_tests will show the custom host tests getting added to the default ones:
```
+---------------+---------------------------------------------------------------------+---------------------------------------------------------------------------------------+
| name          | class                                                               | origin                                                                                |
+---------------+---------------------------------------------------------------------+---------------------------------------------------------------------------------------+
| default       | <class 'mbed_host_tests.host_tests.default_auto.DefaultAuto'>       | mbed-host-tests                                                                       |
| default_auto  | <class 'mbed_host_tests.host_tests.default_auto.DefaultAuto'>       | mbed-host-tests                                                                       |
| detect_auto   | <class 'mbed_host_tests.host_tests.detect_auto.DetectPlatformTest'> | mbed-host-tests                                                                       |
| dev_null_auto | <class 'mbed_host_tests.host_tests.dev_null_auto.DevNullTest'>      | mbed-host-tests                                                                       |
| echo          | <class 'mbed_host_tests.host_tests.echo.EchoTest'>                  | mbed-host-tests                                                                       |
| hello_auto    | <class 'mbed_host_tests.host_tests.hello_auto.HelloTest'>           | mbed-host-tests                                                                       |
| lwm2m         | <class 'lwm2m.Lwm2m'>                                               | C:\files\mbed\staging\framework\test-server-dependencies\greentea-host-tests\lwm2m.py |
| rtc_auto      | <class 'mbed_host_tests.host_tests.rtc_auto.RTCTest'>               | mbed-host-tests                                                                       |
| wait_us_auto  | <class 'mbed_host_tests.host_tests.wait_us_auto.WaitusTest'>        | mbed-host-tests                                                                       |
+---------------+---------------------------------------------------------------------+---------------------------------------------------------------------------------------+
```

### PR DESCRIPTION
**Pull request by theotherjimmy**
Resolves #217

### CODE REVIEW

**Comment by theotherjimmy** [comment]
@Alex-EEE Does this fix `-e` for you?

**Comment by Alex-EEE** [comment]
Let me take some time out later today to test it, I'll try to get back to you by tomorrow morning.

**Comment by Alex-EEE** [comment]
Sorry for the delay, I got sick end of last week :-/

When I run this fork, I get the following Python runtime error:

2018-10-09T22:30:42.6237544Z   File "c:\firmware\tfs-agent\_work\1\s\toolchains\htrun\mbed_host_tests\host_tests_registry\host_registry.py", line 91, in register_from_path
2018-10-09T22:30:42.6237544Z     f for f in listdir(path)
2018-10-09T22:30:42.6247307Z NameError: global name 'listdir' is not defined

**Comment by theotherjimmy** [comment]
@Alex-EEE I hope your feeling better. Sorry about that listdir issue. I don't know why my testing did not run into that bit of code.

**Comment by Alex-EEE** [comment]
I'm seeing a few more import bugs...I started to fix them, but now I'm not even sure where some of these functions are supposed to be coming from.  Here's a list from my linter ( which may be giving too many errors, but they look un imported at first glance: )  join, inspect, BaseHostTest, abspath, imp.  

I added one line already:
from os.path import isfile

**Comment by theotherjimmy** [comment]
Turns out my linter was not running. That explains a lot. @Alex-EEE I got the imports, I think.

**Comment by theotherjimmy** [comment]
That is gross.

**Comment by Alex-EEE** [comment]
Had to add 3 more imports:
import os
import imp
import inspect

but then it worked like a charm!  thanks!

**Comment by theotherjimmy** [comment]
Hi @Alex-EEE, 

Where did you add those imports? I removed all references to `os.` and `imp.` is deprecated and the last commit made a backwards compatibility wrapper for python 3.

**Comment by Alex-EEE** [comment]
Nevermind, I see now, I hand merged the changes b/c I was being lazy and I missed where those references had been removed.  I think you're good as is!

**Comment by Alex-EEE** [comment]
I think I spoke too soon.  Can you try a test and see if it passes on your end? Platform-system-reset?  I got the following error:

2018-10-18T08:07:23.9261463Z [1539850043.93][CONN][INF] found KV pair in stream: {{{{__host_test_name;system_reset}}}}, queued...
2018-10-18T08:07:23.9418029Z [1539850043.94][HTST][ERR] host test not detected: system_reset


FYI, this was how the call to htrun looked, passing in the -e to add an extra folder
2018-10-18T08:07:11.2879257Z 	calling mbedhtrun: mbedhtrun -m K64F -p COM3:9600 -f "BUILD/tests/K64F/mbed/mbed-os/TESTS/mbed_platform/system_reset/system_reset.bin" -e "../test-server-dependencies/greentea-host-tests" -d F: -c jlink -t 0240000036934e45003840149f3500430e61000097969900 -r default -C 4 --sync 5 -P 60

**Comment by theotherjimmy** [comment]
@Alex-EEE That looks like it's in greentea, actually. https://github.com/ARMmbed/greentea/blob/master/mbed_greentea/mbed_test_api.py#L235-L258

**Comment by theotherjimmy** [comment]
You could try running the same test without `-e` to see what it specifies to htrun.

**Comment by Alex-EEE** [comment]
I need the -e though to add our folder of custom host tests.  Is there some other method I should use?

**Comment by theotherjimmy** [comment]
@Alex-EEE `system_reset` is not a built in host test, because it's not in https://github.com/ARMmbed/htrun/tree/master/mbed_host_tests/host_tests. You actually need to specify 2 paths to htrun, and probably 2 paths to greentea as well. This will have to come with a PR to greentea as well to enable multiple `-e` over there as well. This is the part where I grumble about having to do this in 2 places.

**Comment by Alex-EEE** [comment]
I might have misunderstood where this fix went.  so does -e take in a list of folders now...and do you need to supply both the default tests AND a folder of custom tests?

**Comment by Alex-EEE** [comment]
Ok, I see now that system_reset.py lives in TESTS/host_tests.  How many folders are there of host tests supporting mbed-os?

**Comment by theotherjimmy** [comment]
>do you need to supply both the default tests AND a folder of custom tests? 

Looking at greentea, if you don't specify a custom folder, it finds a good "default". This is also supplied to htrun as a custom folder. You would have to find a way to specify both or alternate between them.

**Comment by theotherjimmy** [comment]
>How many folders are there of host tests supporting mbed-os?

./TESTS/host_tests
./features/storage/filesystem/littlefs/TESTS/host_tests

**Comment by Alex-EEE** [comment]
I see.  So is greentea specifying /TESTS/host_tests via the -e parameter to htrun?  Meaning you can't specify another folder via -e to "mbed test run"?

**Pull request merged**
