### PR TITLE
Fix echo tests and set expiration timeout to 600 sec

### PR DESCRIPTION
**Pull request by studavekar**
These are stability fixes 

1) Fix echo tests
2) set expiration  timeout 600 secs

### CODE REVIEW

**Comment by studavekar** [comment]
circleci failure doesn't look like related to this change 
```
  File "/usr/lib/python2.7/unittest/loader.py", line 100, in loadTestsFromName
    parent, obj = obj, getattr(obj, part)
AttributeError: 'module' object has no attribute 'mps2_reset'
```

**Comment by jupe** [comment]
default expiration is one hour in server side, so this now will reduce it to 5 min which might causes unexpectedly failures for tests which takes longer.. If original reason for smaller expiration was ensure that resources get released sooner in corner cases maybe this is kind of reasonable but because even flashing could take more than 5 min in worst scenario default value should be much longer. I would stay in default value still.. Perhaps original problem could be avoided with #189..

**Comment by theotherjimmy** [comment]
@studavekar Rebase/merge needed.

**Comment by theotherjimmy** [comment]
@studavekar I'm closing this as I can't take it without that rebase/merge. Please reopen if you still need it.

**Pull request closed without merging**
