### PR TITLE
Refactor code to be compatible with python3

### PR DESCRIPTION
**Pull request by scartmell-arm**
Fixed issues with python3 compatibility, most were highlighted by the 2to3 conversion tool.

### CODE REVIEW

**Comment by theotherjimmy** [comment]
Nicely done @scartmell-arm. Could you also update the travis.yml to build this with python 3 as well?

**Comment by theotherjimmy** [comment]
I just tried this. Could you add the encoding specifier to the `setup.py` open calls?

**Comment by theotherjimmy** [comment]
@scartmell-arm Thanks for the update. I think this should be good to go, but Circle does not seem to be running the CI 3 times, each with a different version of python. That's annoying.

**Comment by scartmell-arm** [comment]
Hm. Circle CI doesn't seem to support the travis build matrix. It only seems to be doable through their [Circle CI Workflows ](https://circleci.com/docs/2.0/workflows/) or third party [circleci-matrix](https://github.com/michaelcontento/circleci-matrix)

**Comment by theotherjimmy** [comment]
It looks like the plan was to enable travis at some point... @mazimkhan is this the case? Or should we convert the .travis.yml into a circle CI file?

**Comment by mazimkhan** [comment]
Some how the repo was not active on travis. Activated it now. But it may only trigger with another push.

**Comment by theotherjimmy** [comment]
LGTM.  Merging.

**Pull request merged**
