### PR TITLE
Rename most modules to reduce redundancy in import paths

### LINKED ISSUE #173: All of the sub-modules start with `host_tests`
This is very very redundant. I'm not sure if anyone even imports them.

### PR DESCRIPTION
**Pull request by theotherjimmy**
Resolves #173

### CODE REVIEW

**Comment by studavekar** [comment]
@theotherjimmy thanks for bringing these changes. quick try of htrun as an independent entity works well(locally and with --grm), however integration with greentea looks  broken 

```
[mbed] Exec "mbedgt --test-spec ./BUILD/tests/K64F/GCC_ARM/test_spec.json -n tests-mbed_drivers-lp_ticker -V" in "/home/arm/repos/mbed-os"
Traceback (most recent call last):
  File "/home/arm/repos/envhtrun/bin/mbedgt", line 11, in <module>
    load_entry_point('mbed-greentea', 'console_scripts', 'mbedgt')()
  File "/home/arm/repos/greentea/mbed_greentea/mbed_greentea_cli.py", line 212, in main
    copy_methods_str = "Plugin support: " + ', '.join(mbed_host_tests.host_tests_plugins.get_plugin_caps('CopyMethod'))
AttributeError: 'module' object has no attribute 'host_tests_plugins'
[mbed] ERROR: "mbedgt" returned error.

```

**Comment by theotherjimmy** [comment]
Yeah, greentea needs to be updated in tandem. The API containing "host_test[s]" after literally every "." is annoying.

**Comment by theotherjimmy** [comment]
Also, this got the thinking that The `copy_` and `reset_` plugins are not loaded by filesystem, so they could be in the same file. That could make the code base 1 step easier to navigate, as all "jlink" stuff is in one file.

**Comment by theotherjimmy** [comment]
OTOH, I could make aliases at the root for the old imports...

**Comment by theotherjimmy** [comment]
I'm going to make aliases.

**Comment by theotherjimmy** [comment]
@bridadan Aliases added.

**Comment by theotherjimmy** [comment]
I did not move "host_tests_toolbox" because I still don't know what that's supposed to be.

**Comment by theotherjimmy** [comment]
It seems neither "host_tests" or "toolbox" related.

**Comment by theotherjimmy** [comment]
Ugh. This is why you don't put code into `__init__.py`

**Comment by theotherjimmy** [comment]
@bridadan What does the `host_tests_toolbox` module do in 1-2 words?

**Comment by bridadan** [comment]
> What does the host_tests_toolbox module do in 1-2 words?

😮 
"Flash/Reset" - 2 words!

I don't actually know, I can't find anything that uses it (except Mbed CLI). Looks like it was added as part of this big refactor PR: https://github.com/ARMmbed/htrun/pull/65 But also looks like it was never used.

**Comment by theotherjimmy** [comment]
Actually, `mbed_host_test.flash_reset` is a better name: at least I know what's going on.

Would it make more sense.

**Comment by bridadan** [comment]
Yeah probably, though I don't think we should rename it quite yet, just because we don't know if other things are depending on it. We could revisit it in another PR?

**Comment by theotherjimmy** [comment]
We certainly can revisit it.

**Comment by bridadan** [comment]
Tracked here: https://github.com/ARMmbed/htrun/issues/220

**Comment by theotherjimmy** [comment]
Thanks for opening the tracking issue.

**Comment by theotherjimmy** [comment]
Leaving this for another day.

**Pull request closed without merging**
