### PR TITLE
Separate Event Loop from DefaultTestSelector class

### PR DESCRIPTION
**Pull request by ConorPKeegan**
# Changes
* Removed the event loop from DefaultTestSelector class
* Added a BaseEventLoop class to represent the common attributes of event loops
* Added an EventLoop class for the separated event loop, with the common event loop attributes inherited from the Base class
* Added a factory to generate an event loop from a name and a configuration

# Implements
* Implements enhancement #112 

# Replaces
* Replaces Pull request #113, to change the destination branch from `master` to `devel_framework_refactoring`

### CODE REVIEW

**Comment by ConorPKeegan** [comment]
@PrzemekWirkus Here is the new pull request

**Comment by ConorPKeegan** [comment]
@PrzemekWirkus Here are the tests that I have already completed. Coverage has gone down to 39%, but this is because there is no testing on the default event loop yet.

**Comment by PrzemekWirkus** [comment]
+1
This will land in our development branch `devel_framework_refactoring`. We can continue from there :)

**Comment by PrzemekWirkus** [comment]
@ConorPKeegan Coverage looks good for non-default event loop! We can add tests later to tit!
```
Name                                                             Stmts   Miss  Cover
------------------------------------------------------------------------------------
mbed_host_tests\host_tests_event_loop\__init__.py                    3      0   100%
mbed_host_tests\host_tests_event_loop\base_event_loop.py            46      4    91%
mbed_host_tests\host_tests_event_loop\default_event_loop.py        139    119    14%
mbed_host_tests\host_tests_event_loop\event_loop.py                 11      1    91%
```

**Pull request merged**
