### PR TITLE
Intervaltree version update (3.0.0) caused builds to break.

### PR DESCRIPTION
**Pull request by aashishc1988**
As indicated in https://github.com/ARMmbed/mbed-os/pull/9131, 
Capping version to latest 2.x

**Pull request type**
[x] Fix
[ ] Refactor
[ ] Target update
[ ] Functionality change
[ ] Docs update
[ ] Test update
[ ] Breaking change

### CODE REVIEW

**Comment by aashishc1988** [comment]
@bridadan @cmonr

**Comment by bridadan** [comment]
Just chatted with pyocd folks offline, sounds like they'll try to get a release out today that pins the version. I'd prefer to leave the requirement in pyocd if possible since we don't depend on it directly. Anyone have any strong feelings otherwise?

**Comment by bridadan** [comment]
Looks like pyocd got a release out: https://github.com/mbedmicro/pyOCD/releases/tag/v0.14.2

Ok to close this @aashishc1988?

**Comment by aashishc1988** [comment]
Considering we have pyocd release now which pins the version, I am closing this one.

**Pull request closed without merging**
