### PR TITLE
Aborting mechanism when parent process wants to stop mbedhtrun

### PR DESCRIPTION
**Pull request by mazimkhan**
Fix for issue https://github.com/ARMmbed/greentea/issues/48

Changes:
 - Added a stdin monitoring thread
 - Aborting selector when stdin is closed.
 - Check for abort at different steps of execution.
 - Selector aborts test case.
 - Added new based class method abort().

Creating PR for feedback from issue creator. Unit tests will be added soon.

This PR is complimentary to https://github.com/ARMmbed/greentea/pull/63 (they should come at the same time in release.

### CODE REVIEW

**Comment by autopulated** [comment]
From some experience trying to do things like this cleanly: the handling of file polling can vary substantially between platforms, so it's worth double-checking that this works as intended across windows, mac and linux!

**Comment by mazimkhan** [comment]
@autopulated thanks for reminding. I have cross platform testing in mind. This PR is more for @0xc0170 to test in his environment. 
I aware that read may break for EAGAIN and EINTR on Linux. Havn't used mac ever. Any specific things I should be careful about?

**Comment by PrzemekWirkus** [comment]
@mazimkhan BTW, we've replaced rampUp/rampDown with setup/teardown.

**Comment by mazimkhan** [comment]
@PrzemekWirkus @stegut01   please review this PR as well.

**Comment by PrzemekWirkus** [comment]
I will review it today! :)

**Pull request merged**
