### PR TITLE
[issue 48] Rename rampUp/Down to setup/teardown

### PR DESCRIPTION
**Pull request by stegut01**
Fixes issue #48

### CODE REVIEW

**Comment by 0xc0170** [comment]
One question , I noticed all functions in this module are using lower case names, why rumpUp and Down are an exception? now setUp/tearDown. I assume it's to be aligned with other tools (I noticed in cli test they use camel case for functions). Which makes a question of if this compatibility makes sense (adding new API will follow which one?), either to use one or another?

**Comment by PrzemekWirkus** [comment]
Like I said, rampUp/rampDown was "copied" from Jussi's framework and names there were camel case.
We will align with module's (Pythonic) coding styles.

**Comment by PrzemekWirkus** [comment]
@stegut01 Stefan, please rename ```tearDown``` to ```teardown```, see [coding styles](https://github.com/ARMmbed/greentea/blob/master/docs/CONTRIBUTING.md#naming) for our tools.

**Comment by PrzemekWirkus** [comment]
+1

**Comment by 0xc0170** [comment]
:clap:

**Pull request merged**
