### PR TITLE
Use PrettyTable with GitHub policy

### PR DESCRIPTION
**Pull request by jeromecoutant**
This is following ARMmbed/greentea#277 discussion

### CODE REVIEW

**Comment by jeromecoutant** [comment]
For information, here is all related PR :

- https://github.com/ARMmbed/mbed-os/pull/7720
- https://github.com/ARMmbed/greentea/pull/279
- https://github.com/ARMmbed/mbed-ls/pull/383
- https://github.com/ARMmbed/htrun/pull/208

**Comment by theotherjimmy** [comment]
I'm making a release right now, It'll be a patch release, so I'm merging this **after** I make that release.

**Comment by jeromecoutant** [comment]
Hi
For information, this is not in a released version. Is it planned ?
Thx

**Comment by cmonr** [comment]
@jeromecoutant Are you on 1.4.2?

https://github.com/ARMmbed/htrun/releases/tag/v1.4.2

**Comment by jeromecoutant** [comment]
OK, sorry, I have checked the github label (as for mbed-os)
Thx

**Pull request merged**
